import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../common/audit/audit.service';
import { AuthenticatedPrincipal } from '../common/auth/auth.types';
import { CancelSubscriptionDto, CreatePlanDto, CreateSubscriptionDto, ExtendSubscriptionDto, PaymentDto, SubscriptionHistoryQueryDto, UpdatePlanDto } from './dto/subscription.dto';

@Injectable()
export class SubscriptionsService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  listPlans() { return this.prisma.subscriptionPlan.findMany({ orderBy: { pricePkr: 'asc' } }); }
  async createPlan(dto: CreatePlanDto, actor: AuthenticatedPrincipal, requestId: string) { try { const plan = await this.prisma.subscriptionPlan.create({ data: dto }); await this.audit.write({ actorId: actor.id, action: 'subscription.plan_create', resource: 'subscription_plan', resourceId: plan.id, outcome: 'SUCCESS', requestId }); return plan; } catch (e) { if ((e as { code?: string }).code === 'P2002') throw new ConflictException('Plan code already exists'); throw e; } }
  async updatePlan(id: string, dto: UpdatePlanDto, actor: AuthenticatedPrincipal, requestId: string) { const plan = await this.prisma.subscriptionPlan.update({ where: { id }, data: dto }); await this.audit.write({ actorId: actor.id, action: 'subscription.plan_update', resource: 'subscription_plan', resourceId: id, outcome: 'SUCCESS', requestId }); return plan; }
  async subscribe(dto: CreateSubscriptionDto, actor: AuthenticatedPrincipal, requestId: string) {
    const plan = await this.prisma.subscriptionPlan.findFirst({ where: { id: dto.planId, isActive: true } });
    if (!plan) throw new NotFoundException('Active plan not found');
    const user = await this.prisma.user.findFirst({ where: { id: dto.userId, deletedAt: null }, select: { id: true } });
    if (!user) throw new NotFoundException('User not found');
    const now = new Date();
    const current = await this.prisma.subscription.findFirst({ where: { userId: dto.userId, status: 'ACTIVE', endsAt: { gt: now } }, orderBy: { endsAt: 'desc' } });
    const startsAt = current?.endsAt && current.endsAt > now ? current.endsAt : now;
    const endsAt = new Date(startsAt.getTime() + plan.durationDays * 86_400_000);
    const subscription = await this.prisma.$transaction(async (tx) => { const item = await tx.subscription.create({ data: { userId: dto.userId, planId: dto.planId, startsAt, endsAt, note: dto.note } }); await tx.subscriptionHistory.create({ data: { subscriptionId: item.id, actorId: actor.id, action: 'created', newStartsAt: startsAt, newEndsAt: endsAt, note: dto.note } }); return item; });
    await this.audit.write({ actorId: actor.id, action: 'subscription.create', resource: 'subscription', resourceId: subscription.id, outcome: 'SUCCESS', requestId, metadata: { userId: dto.userId, planId: dto.planId } });
    return subscription;
  }
  async listForUser(userId: string, actor: AuthenticatedPrincipal, query: SubscriptionHistoryQueryDto) { if (actor.id !== userId && !actor.permissions.includes('subscriptions.read') && !actor.roles.includes('SUPER_ADMIN')) throw new NotFoundException('Subscription not found'); const where = { userId }; const [items, total] = await this.prisma.$transaction([this.prisma.subscription.findMany({ where, include: { plan: true, history: { orderBy: { createdAt: 'desc' }, take: 20 } }, orderBy: { startsAt: 'desc' }, skip: (query.page - 1) * query.limit, take: query.limit }), this.prisma.subscription.count({ where })]); return { items, page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) }; }
  async recordPayment(dto: PaymentDto, actor: AuthenticatedPrincipal, requestId: string) { const user = await this.prisma.user.findFirst({ where: { id: dto.userId, deletedAt: null }, select: { id: true } }); if (!user) throw new NotFoundException('User not found'); const payment = await this.prisma.paymentRecord.create({ data: { userId: dto.userId, planId: dto.planId, actorId: actor.id, amountPkr: dto.amountPkr, method: dto.method, reference: dto.reference, proofKey: dto.proofKey, note: dto.note, paidAt: dto.paidAt ? new Date(dto.paidAt) : new Date() } }); await this.audit.write({ actorId: actor.id, action: 'subscription.payment_record', resource: 'payment', resourceId: payment.id, outcome: 'SUCCESS', requestId }); return payment; }
  async extend(id: string, dto: ExtendSubscriptionDto, actor: AuthenticatedPrincipal, requestId: string) { const current = await this.prisma.subscription.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Subscription not found'); const endsAt = new Date(Math.max(current.endsAt.getTime(), Date.now()) + dto.days * 86_400_000); const updated = await this.prisma.$transaction(async (tx) => { const item = await tx.subscription.update({ where: { id }, data: { endsAt, status: 'ACTIVE', cancelledAt: null } }); await tx.subscriptionHistory.create({ data: { subscriptionId: id, actorId: actor.id, action: 'extended', oldStartsAt: current.startsAt, oldEndsAt: current.endsAt, newStartsAt: current.startsAt, newEndsAt: endsAt, note: dto.note } }); return item; }); await this.audit.write({ actorId: actor.id, action: 'subscription.extend', resource: 'subscription', resourceId: id, outcome: 'SUCCESS', requestId }); return updated; }
  async cancel(id: string, dto: CancelSubscriptionDto, actor: AuthenticatedPrincipal, requestId: string) { const current = await this.prisma.subscription.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Subscription not found'); const updated = await this.prisma.$transaction(async (tx) => { const item = await tx.subscription.update({ where: { id }, data: { status: 'CANCELLED', cancelledAt: new Date(), note: dto.note ?? current.note } }); await tx.subscriptionHistory.create({ data: { subscriptionId: id, actorId: actor.id, action: 'cancelled', oldStartsAt: current.startsAt, oldEndsAt: current.endsAt, newStartsAt: current.startsAt, newEndsAt: current.endsAt, note: dto.note } }); return item; }); await this.audit.write({ actorId: actor.id, action: 'subscription.cancel', resource: 'subscription', resourceId: id, outcome: 'SUCCESS', requestId }); return updated; }
  async validate(userId: string) { const now = new Date(); const subscription = await this.prisma.subscription.findFirst({ where: { userId, status: 'ACTIVE', startsAt: { lte: now }, endsAt: { gt: now } }, include: { plan: true }, orderBy: { endsAt: 'desc' } }); return { active: Boolean(subscription), subscription }; }
}
