import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../common/audit/audit.service';
import { AuthenticatedPrincipal } from '../common/auth/auth.types';
import { AssignPermissionDto, AssignRoleDto, AssignRolePermissionDto, CreatePermissionDto, CreateRoleDto, UpdatePermissionDto, UpdateRoleDto } from './dto/rbac.dto';

@Injectable()
export class RbacService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  listRoles() { return this.prisma.roleDefinition.findMany({ include: { permissions: { include: { permission: true } }, _count: { select: { users: true } } }, orderBy: { code: 'asc' } }); }
  async createRole(dto: CreateRoleDto, actor: AuthenticatedPrincipal, requestId: string) { try { const role = await this.prisma.roleDefinition.create({ data: dto }); await this.audit.write({ actorId: actor.id, action: 'rbac.role_create', resource: 'role', resourceId: role.id, outcome: 'SUCCESS', requestId }); return role; } catch (e) { if ((e as { code?: string }).code === 'P2002') throw new ConflictException('Role already exists'); throw e; } }
  async updateRole(id: string, dto: UpdateRoleDto, actor: AuthenticatedPrincipal, requestId: string) { const role = await this.prisma.roleDefinition.update({ where: { id }, data: dto }); await this.audit.write({ actorId: actor.id, action: 'rbac.role_update', resource: 'role', resourceId: id, outcome: 'SUCCESS', requestId }); return role; }
  async deleteRole(id: string, actor: AuthenticatedPrincipal, requestId: string) { const role = await this.prisma.roleDefinition.findUnique({ where: { id } }); if (!role) throw new NotFoundException('Role not found'); if (role.systemManaged) throw new ConflictException('System roles cannot be deleted'); await this.prisma.roleDefinition.delete({ where: { id } }); await this.audit.write({ actorId: actor.id, action: 'rbac.role_delete', resource: 'role', resourceId: id, outcome: 'SUCCESS', requestId }); return { success: true }; }
  listPermissions() { return this.prisma.permission.findMany({ orderBy: { code: 'asc' } }); }
  findRole(id: string) { return this.prisma.roleDefinition.findUniqueOrThrow({ where: { id }, include: { permissions: { include: { permission: true } }, _count: { select: { users: true } } } }); }
  async createPermission(dto: CreatePermissionDto, actor: AuthenticatedPrincipal, requestId: string) { try { const permission = await this.prisma.permission.create({ data: dto }); await this.audit.write({ actorId: actor.id, action: 'rbac.permission_create', resource: 'permission', resourceId: permission.id, outcome: 'SUCCESS', requestId }); return permission; } catch (e) { if ((e as { code?: string }).code === 'P2002') throw new ConflictException('Permission already exists'); throw e; } }
  async updatePermission(id: string, dto: UpdatePermissionDto, actor: AuthenticatedPrincipal, requestId: string) { const permission = await this.prisma.permission.update({ where: { id }, data: dto }); await this.audit.write({ actorId: actor.id, action: 'rbac.permission_update', resource: 'permission', resourceId: id, outcome: 'SUCCESS', requestId }); return permission; }
  async deletePermission(id: string, actor: AuthenticatedPrincipal, requestId: string) { try { await this.prisma.permission.delete({ where: { id } }); } catch (e) { if ((e as { code?: string }).code === 'P2025') throw new NotFoundException('Permission not found'); throw e; } await this.audit.write({ actorId: actor.id, action: 'rbac.permission_delete', resource: 'permission', resourceId: id, outcome: 'SUCCESS', requestId }); return { success: true }; }
  async assignRole(userId: string, dto: AssignRoleDto, actor: AuthenticatedPrincipal, requestId: string) { const role = await this.prisma.roleDefinition.findUnique({ where: { code: dto.role } }); if (!role) throw new NotFoundException('Role not found'); await this.prisma.userRole.upsert({ where: { userId_roleId: { userId, roleId: role.id } }, create: { userId, roleId: role.id }, update: {} }); await this.audit.write({ actorId: actor.id, action: 'rbac.user_role_assign', resource: 'user', resourceId: userId, outcome: 'SUCCESS', requestId, metadata: { role: dto.role } }); return { success: true }; }
  async removeRole(userId: string, dto: AssignRoleDto, actor: AuthenticatedPrincipal, requestId: string) { const role = await this.prisma.roleDefinition.findUnique({ where: { code: dto.role } }); if (!role) throw new NotFoundException('Role not found'); await this.prisma.userRole.deleteMany({ where: { userId, roleId: role.id } }); await this.audit.write({ actorId: actor.id, action: 'rbac.user_role_remove', resource: 'user', resourceId: userId, outcome: 'SUCCESS', requestId, metadata: { role: dto.role } }); return { success: true }; }
  async assignRolePermission(roleId: string, dto: AssignRolePermissionDto, actor: AuthenticatedPrincipal, requestId: string) { await this.prisma.rolePermission.upsert({ where: { roleId_permissionId: { roleId, permissionId: dto.permissionId } }, create: { roleId, permissionId: dto.permissionId }, update: {} }); await this.audit.write({ actorId: actor.id, action: 'rbac.role_permission_assign', resource: 'role', resourceId: roleId, outcome: 'SUCCESS', requestId, metadata: { permissionId: dto.permissionId } }); return { success: true }; }
  async removeRolePermission(roleId: string, permissionId: string, actor: AuthenticatedPrincipal, requestId: string) { await this.prisma.rolePermission.deleteMany({ where: { roleId, permissionId } }); await this.audit.write({ actorId: actor.id, action: 'rbac.role_permission_remove', resource: 'role', resourceId: roleId, outcome: 'SUCCESS', requestId, metadata: { permissionId } }); return { success: true }; }
  async assignUserPermission(userId: string, dto: AssignPermissionDto, actor: AuthenticatedPrincipal, requestId: string) { await this.prisma.userPermission.upsert({ where: { userId_permissionId: { userId, permissionId: dto.permissionId } }, create: { userId, permissionId: dto.permissionId, granted: dto.granted ?? true }, update: { granted: dto.granted ?? true } }); await this.audit.write({ actorId: actor.id, action: 'rbac.user_permission_assign', resource: 'user', resourceId: userId, outcome: 'SUCCESS', requestId, metadata: { permissionId: dto.permissionId, granted: dto.granted ?? true } }); return { success: true }; }
  async removeUserPermission(userId: string, permissionId: string, actor: AuthenticatedPrincipal, requestId: string) { await this.prisma.userPermission.deleteMany({ where: { userId, permissionId } }); await this.audit.write({ actorId: actor.id, action: 'rbac.user_permission_remove', resource: 'user', resourceId: userId, outcome: 'SUCCESS', requestId, metadata: { permissionId } }); return { success: true }; }
}
