import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, RoleCode } from '@prisma/client';
import { Request } from 'express';
import * as argon2 from 'argon2';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../common/audit/audit.service';
import { AuthenticatedPrincipal } from '../common/auth/auth.types';
import { FirebasePushService } from './firebase-push.service';
import { StorageProviderAdapter } from '../media-gateway/storage-provider.adapter';
import {
  AccountDeletionRequestDto, AdminRoleDto, AssignTrendingDto, CreateAdminDto, CreateBannerDto, CreateCommentDto, CreateNotificationDto, CreateReleaseDto, CreateSubscriptionRequestDto, LegacyListDto, MarkMessageDto, MessageListDto, RecordViewDto, RemoteConfigDto, ReviewAccountDeletionRequestDto, ReviewSubscriptionRequestDto, SearchDto, SecurityBlockDto, SecurityIncidentDto, SendGroupMessageDto, SendMessageDto, SubscriptionSettingsDto, UpdateBannerDto, UpdateCommentDto, UpdateNotificationDto, UpdateReleaseDto, UpdateTrendingDto,
} from './legacy.dto';

const DEFAULT_SETTINGS_ID = '00000000-0000-0000-0000-000000000001';
const ADMIN_ROLES: RoleCode[] = [RoleCode.SUPER_ADMIN, RoleCode.ADMIN, RoleCode.SUB_ADMIN, RoleCode.MODERATOR];

@Injectable()
export class LegacyService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly push: FirebasePushService, private readonly provider: StorageProviderAdapter) {}

  async latestNotification() { return this.prisma.notification.findFirst({ where: { deletedAt: null }, orderBy: { createdAt: 'desc' }, select: { id: true, title: true, message: true, imageKey: true, createdAt: true } }); }
  async listNotifications(query: LegacyListDto) { const where = { deletedAt: null, ...(query.search ? { OR: [{ title: { contains: query.search, mode: 'insensitive' as const } }, { message: { contains: query.search, mode: 'insensitive' as const } }] } : {}) }; return this.page(this.prisma.notification, where, query, { createdAt: query.order }, { id: true, title: true, message: true, imageKey: true, createdAt: true, updatedAt: true }); }
  async createNotification(dto: CreateNotificationDto, actor: AuthenticatedPrincipal, requestId: string) { const item = await this.prisma.notification.create({ data: { createdById: actor.id, title: dto.title.trim(), message: dto.message.trim(), imageKey: dto.imageKey } }); await this.audit.write({ actorId: actor.id, action: 'legacy.notification_create', resource: 'notification', resourceId: item.id, outcome: 'SUCCESS', requestId }); return item; }
  async updateNotification(id: string, dto: UpdateNotificationDto, actor: AuthenticatedPrincipal, requestId: string) { const item = await this.prisma.notification.update({ where: { id }, data: { title: dto.title.trim(), message: dto.message.trim(), imageKey: dto.imageKey } }); await this.audit.write({ actorId: actor.id, action: 'legacy.notification_update', resource: 'notification', resourceId: id, outcome: 'SUCCESS', requestId }); return item; }
  async deleteNotification(id: string, actor: AuthenticatedPrincipal, requestId: string) { const item = await this.prisma.notification.updateMany({ where: { id, deletedAt: null }, data: { deletedAt: new Date() } }); if (!item.count) throw new NotFoundException('Notification not found'); await this.audit.write({ actorId: actor.id, action: 'legacy.notification_delete', resource: 'notification', resourceId: id, outcome: 'SUCCESS', requestId }); return { success: true }; }
  async sendNotification(id: string, actor: AuthenticatedPrincipal, requestId: string) { const notification = await this.prisma.notification.findFirst({ where: { id, deletedAt: null } }); if (!notification) throw new NotFoundException('Notification not found'); const users = await this.prisma.user.findMany({ where: { status: 'ACTIVE', deletedAt: null, deviceToken: { not: null } }, select: { deviceToken: true } }); const delivery = await this.push.send(users.map((user) => user.deviceToken ?? ''), notification.title, notification.message, { notification_id: notification.id }); await this.audit.write({ actorId: actor.id, action: 'legacy.notification_send', resource: 'notification', resourceId: id, outcome: 'SUCCESS', requestId, metadata: delivery }); return { notification, delivery }; }
  async markNotificationRead(id: string, actor: AuthenticatedPrincipal) { const notification = await this.prisma.notification.findFirst({ where: { id, deletedAt: null }, select: { id: true } }); if (!notification) throw new NotFoundException('Notification not found'); await this.prisma.notificationRecipient.upsert({ where: { notificationId_userId: { notificationId: id, userId: actor.id } }, create: { notificationId: id, userId: actor.id, readAt: new Date() }, update: { readAt: new Date() } }); return { success: true }; }
  async listMobileNotifications(actor: AuthenticatedPrincipal, query: LegacyListDto) {
    const where = { deletedAt: null, ...(query.search ? { OR: [{ title: { contains: query.search, mode: 'insensitive' as const } }, { message: { contains: query.search, mode: 'insensitive' as const } }] } : {}) };
    const [items, total] = await this.prisma.$transaction([
      this.prisma.notification.findMany({ where, orderBy: { createdAt: query.order }, skip: (query.page - 1) * query.limit, take: query.limit, select: { id: true, title: true, message: true, imageKey: true, createdAt: true, recipients: { where: { userId: actor.id }, select: { readAt: true } } } }),
      this.prisma.notification.count({ where }),
    ]);
    return { items: items.map((item) => ({ id: item.id, title: item.title, message: item.message, imageKey: item.imageKey, createdAt: item.createdAt, readAt: item.recipients[0]?.readAt ?? null })), page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) };
  }

  async listFavorites(actor: AuthenticatedPrincipal) {
    const items = await this.prisma.favoriteDrama.findMany({
      where: { userId: actor.id, drama: { deletedAt: null, isPublished: true } },
      orderBy: { createdAt: 'desc' },
      select: { id: true, createdAt: true, drama: { select: { id: true, name: true, slug: true, description: true, thumbnailKey: true, isPublished: true } } },
    });
    return items.map((item) => ({ ...item.drama, favoriteId: item.id, favoritedAt: item.createdAt }));
  }

  async addFavorite(dramaId: string, actor: AuthenticatedPrincipal, requestId: string) {
    const drama = await this.prisma.drama.findFirst({ where: { id: dramaId, deletedAt: null, isPublished: true }, select: { id: true } });
    if (!drama) throw new NotFoundException('Drama not found');
    const item = await this.prisma.favoriteDrama.upsert({
      where: { userId_dramaId: { userId: actor.id, dramaId } },
      create: { userId: actor.id, dramaId },
      update: {},
      select: { id: true, dramaId: true, createdAt: true },
    });
    await this.audit.write({ actorId: actor.id, action: 'mobile.favorite_add', resource: 'drama', resourceId: dramaId, outcome: 'SUCCESS', requestId });
    return item;
  }

  async removeFavorite(dramaId: string, actor: AuthenticatedPrincipal, requestId: string) {
    const result = await this.prisma.favoriteDrama.deleteMany({ where: { userId: actor.id, dramaId } });
    await this.audit.write({ actorId: actor.id, action: 'mobile.favorite_remove', resource: 'drama', resourceId: dramaId, outcome: 'SUCCESS', requestId, metadata: { removed: result.count } });
    return { success: true };
  }

  async listMessages(actor: AuthenticatedPrincipal, query: MessageListDto) {
    // Customers may only see their own conversation. Staff with the explicit
    // inbox permission can process all support messages in the admin panel.
    const canReadInbox = actor.permissions.includes('messages.read');
    const where = { ...(canReadInbox ? {} : { userId: actor.id }), ...(query.status ? { status: query.status } : {}) };
    return this.page(this.prisma.userMessage, where, query, { createdAt: 'desc' }, {
      id: true, userId: true, message: true, status: true, createdAt: true, readAt: true,
      sender: { select: { id: true, username: true } },
      user: { select: { id: true, username: true, email: true } },
    });
  }
  async markMessagesRead(actor: AuthenticatedPrincipal, dto: MarkMessageDto) { const where = dto.messageId ? { id: dto.messageId, userId: actor.id } : { userId: actor.id, status: 'unread' }; const result = await this.prisma.userMessage.updateMany({ where, data: { status: 'read', readAt: new Date() } }); return { success: true, updated: result.count }; }
  async sendMessage(dto: SendMessageDto, actor: AuthenticatedPrincipal, requestId: string) { await this.ensureUser(dto.userId); const item = await this.prisma.userMessage.create({ data: { userId: dto.userId, senderId: actor.id, message: dto.message.trim(), status: 'unread' } }); await this.audit.write({ actorId: actor.id, action: 'legacy.message_send', resource: 'user_message', resourceId: item.id, outcome: 'SUCCESS', requestId, metadata: { userId: dto.userId } }); await this.pushToUser(dto.userId, 'New Message', dto.message, { message_id: item.id }); return item; }
  async sendGroupMessage(dto: SendGroupMessageDto, actor: AuthenticatedPrincipal, requestId: string) { const group = await this.prisma.accessGroup.findUnique({ where: { id: dto.groupId }, include: { members: { where: { revokedAt: null, endsAt: { gt: new Date() } }, select: { userId: true } } } }); if (!group) throw new NotFoundException('Group not found'); const rows = [...new Set(group.members.map((member) => member.userId))].map((userId) => ({ userId, senderId: actor.id, groupId: dto.groupId, message: dto.message.trim(), status: 'unread' })); if (rows.length) await this.prisma.userMessage.createMany({ data: rows }); await this.audit.write({ actorId: actor.id, action: 'legacy.group_message_send', resource: 'access_group', resourceId: dto.groupId, outcome: 'SUCCESS', requestId, metadata: { recipients: rows.length } }); const tokens = await this.tokensForUsers(rows.map((row) => row.userId)); const delivery = await this.push.send(tokens, 'New Message', dto.message, { group_id: dto.groupId }); return { success: true, recipients: rows.length, delivery }; }
  async sendAdminNotification(message: string, actor: AuthenticatedPrincipal, requestId: string) { const users = await this.prisma.user.findMany({ where: { status: 'ACTIVE', deletedAt: null, deviceToken: { not: null } }, select: { deviceToken: true } }); const delivery = await this.push.send(users.map((user) => user.deviceToken ?? ''), 'Urdu Bolo', message, { type: 'admin_message' }); await this.audit.write({ actorId: actor.id, action: 'legacy.admin_notification_send', resource: 'user', outcome: 'SUCCESS', requestId, metadata: delivery }); return { success: true, delivery }; }
  async sendMobileSupportMessage(message: string, actor: AuthenticatedPrincipal, requestId: string) {
    const item = await this.prisma.userMessage.create({ data: { userId: actor.id, senderId: actor.id, message: message.trim(), status: 'unread' }, select: { id: true, message: true, status: true, createdAt: true, sender: { select: { id: true, username: true } } } });
    await this.audit.write({ actorId: actor.id, action: 'mobile.support_message_create', resource: 'user_message', resourceId: item.id, outcome: 'SUCCESS', requestId });
    return item;
  }

  async requestAccountDeletion(dto: AccountDeletionRequestDto, actor: AuthenticatedPrincipal, requestId: string) {
    const existing = await this.prisma.accountDeletionRequest.findFirst({ where: { userId: actor.id, status: 'pending' }, select: { id: true, createdAt: true, status: true } });
    if (existing) return existing;
    const item = await this.prisma.accountDeletionRequest.create({
      data: { userId: actor.id, reason: dto.reason?.trim() || null },
      select: { id: true, reason: true, status: true, createdAt: true },
    });
    await this.audit.write({ actorId: actor.id, action: 'mobile.account_deletion_request', resource: 'account_deletion_request', resourceId: item.id, outcome: 'SUCCESS', requestId });
    return item;
  }

  async listOwnAccountDeletionRequests(actor: AuthenticatedPrincipal) {
    return this.prisma.accountDeletionRequest.findMany({ where: { userId: actor.id }, orderBy: { createdAt: 'desc' }, select: { id: true, reason: true, status: true, adminNote: true, reviewedAt: true, createdAt: true } });
  }

  async listAccountDeletionRequests(query: LegacyListDto) {
    const where = query.search ? { user: { OR: [{ username: { contains: query.search, mode: 'insensitive' as const } }, { email: { contains: query.search, mode: 'insensitive' as const } }] } } : {};
    return this.page(this.prisma.accountDeletionRequest, where, query, { createdAt: 'desc' }, { id: true, userId: true, reason: true, status: true, adminNote: true, reviewedAt: true, createdAt: true, user: { select: { id: true, username: true, email: true } } });
  }

  async reviewAccountDeletionRequest(id: string, dto: ReviewAccountDeletionRequestDto, actor: AuthenticatedPrincipal, requestId: string) {
    const current = await this.prisma.accountDeletionRequest.findUnique({ where: { id } });
    if (!current) throw new NotFoundException('Account deletion request not found');
    if (current.status !== 'pending') throw new ConflictException('Account deletion request was already reviewed');
    const item = await this.prisma.accountDeletionRequest.update({ where: { id }, data: { status: dto.status, adminNote: dto.adminNote, reviewedById: actor.id, reviewedAt: new Date() } });
    if (dto.status === 'approved') await this.prisma.user.update({ where: { id: current.userId }, data: { status: 'SUSPENDED', deletedAt: new Date() } });
    await this.audit.write({ actorId: actor.id, action: `legacy.account_deletion_${dto.status}`, resource: 'account_deletion_request', resourceId: id, outcome: 'SUCCESS', requestId, metadata: { userId: current.userId } });
    return item;
  }

  async listBanners(includeInactive = false) { return this.prisma.banner.findMany({ where: { deletedAt: null, ...(includeInactive ? {} : { isActive: true }) }, orderBy: { createdAt: 'desc' } }); }
  async createBanner(dto: CreateBannerDto, actor: AuthenticatedPrincipal, requestId: string) { if (!dto.imageKey && !dto.videoKey) throw new BadRequestException('A banner image or video is required'); const item = await this.prisma.banner.create({ data: dto }); await this.audit.write({ actorId: actor.id, action: 'legacy.banner_create', resource: 'banner', resourceId: item.id, outcome: 'SUCCESS', requestId }); return item; }
  async updateBanner(id: string, dto: UpdateBannerDto, actor: AuthenticatedPrincipal, requestId: string) { const item = await this.prisma.banner.update({ where: { id }, data: dto }); await this.audit.write({ actorId: actor.id, action: 'legacy.banner_update', resource: 'banner', resourceId: id, outcome: 'SUCCESS', requestId }); return item; }
  async deleteBanner(id: string, actor: AuthenticatedPrincipal, requestId: string) { const result = await this.prisma.banner.updateMany({ where: { id, deletedAt: null }, data: { deletedAt: new Date(), isActive: false } }); if (!result.count) throw new NotFoundException('Banner not found'); await this.audit.write({ actorId: actor.id, action: 'legacy.banner_delete', resource: 'banner', resourceId: id, outcome: 'SUCCESS', requestId }); return { success: true }; }

  async listTrending() { return this.prisma.trendingDrama.findMany({ orderBy: { position: 'asc' }, include: { drama: { select: { id: true, name: true, slug: true, thumbnailKey: true } } } }); }
  async assignTrending(dto: AssignTrendingDto, actor: AuthenticatedPrincipal, requestId: string) { await this.ensureDrama(dto.dramaId); try { const item = await this.prisma.trendingDrama.create({ data: dto }); await this.audit.write({ actorId: actor.id, action: 'legacy.trending_assign', resource: 'trending_drama', resourceId: item.id, outcome: 'SUCCESS', requestId }); return item; } catch (error) { if ((error as { code?: string }).code === 'P2002') throw new ConflictException('Drama or position is already trending'); throw error; } }
  async updateTrending(id: string, dto: UpdateTrendingDto, actor: AuthenticatedPrincipal, requestId: string) { try { const item = await this.prisma.trendingDrama.update({ where: { id }, data: dto }); await this.audit.write({ actorId: actor.id, action: 'legacy.trending_update', resource: 'trending_drama', resourceId: id, outcome: 'SUCCESS', requestId }); return item; } catch (error) { if ((error as { code?: string }).code === 'P2002') throw new ConflictException('Drama or position is already trending'); throw error; } }
  async deleteTrending(id: string, actor: AuthenticatedPrincipal, requestId: string) { const result = await this.prisma.trendingDrama.deleteMany({ where: { id } }); if (!result.count) throw new NotFoundException('Trending drama not found'); await this.audit.write({ actorId: actor.id, action: 'legacy.trending_delete', resource: 'trending_drama', resourceId: id, outcome: 'SUCCESS', requestId }); return { success: true }; }

  async latestRelease() { const item = await this.prisma.appRelease.findFirst({ where: { isActive: true }, orderBy: [{ versionCode: 'desc' }, { createdAt: 'desc' }], select: { id: true, versionName: true, versionCode: true, originalName: true, fileSize: true, createdAt: true } }); return item ? { ...item, fileSize: item.fileSize?.toString() ?? null, downloadPath: `/api/v1/app/releases/${item.id}/download` } : null; }
  async listReleases(query: LegacyListDto) { const result = await this.page(this.prisma.appRelease, {}, query, { createdAt: 'desc' }, { id: true, versionName: true, versionCode: true, originalName: true, fileSize: true, isActive: true, createdAt: true, updatedAt: true }); return { ...result, items: result.items.map((item: { fileSize: bigint | null }) => ({ ...item, fileSize: item.fileSize?.toString() ?? null })) }; }
  async createRelease(dto: CreateReleaseDto, actor: AuthenticatedPrincipal, requestId: string) { this.provider.validateUrl(dto.storageKey); const item = await this.prisma.appRelease.create({ data: { ...dto, uploadedById: actor.id } }); await this.audit.write({ actorId: actor.id, action: 'legacy.release_create', resource: 'app_release', resourceId: item.id, outcome: 'SUCCESS', requestId }); return this.publicRelease(item); }
  async updateRelease(id: string, dto: UpdateReleaseDto, actor: AuthenticatedPrincipal, requestId: string) { if (dto.storageKey) this.provider.validateUrl(dto.storageKey); const item = await this.prisma.appRelease.update({ where: { id }, data: dto }); await this.audit.write({ actorId: actor.id, action: 'legacy.release_update', resource: 'app_release', resourceId: id, outcome: 'SUCCESS', requestId }); return this.publicRelease(item); }
  async deleteRelease(id: string, actor: AuthenticatedPrincipal, requestId: string) { const item = await this.prisma.appRelease.updateMany({ where: { id, isActive: true }, data: { isActive: false } }); if (!item.count) throw new NotFoundException('Release not found'); await this.audit.write({ actorId: actor.id, action: 'legacy.release_deactivate', resource: 'app_release', resourceId: id, outcome: 'SUCCESS', requestId }); return { success: true }; }
  async downloadRelease(id: string, range?: string) { const release = await this.prisma.appRelease.findFirst({ where: { id, isActive: true }, select: { storageKey: true, originalName: true, fileSize: true } }); if (!release) throw new NotFoundException('Release not found'); const response = await this.provider.fetch(release.storageKey, range); return { response, originalName: release.originalName, fileSize: release.fileSize }; }

  async getRemoteConfig() { const rows = await this.prisma.remoteConfig.findMany({ where: { isActive: true }, orderBy: { configKey: 'asc' } }); return Object.fromEntries(rows.map((row) => [row.configKey, row.value])); }
  async listRemoteConfig() { return this.prisma.remoteConfig.findMany({ orderBy: { configKey: 'asc' } }); }
  async upsertRemoteConfig(dto: RemoteConfigDto, actor: AuthenticatedPrincipal, requestId: string) { const item = await this.prisma.remoteConfig.upsert({ where: { configKey: dto.configKey }, create: { configKey: dto.configKey, value: dto.value as Prisma.InputJsonValue, isActive: dto.isActive ?? true, updatedById: actor.id }, update: { value: dto.value as Prisma.InputJsonValue, isActive: dto.isActive ?? true, updatedById: actor.id } }); await this.audit.write({ actorId: actor.id, action: 'legacy.remote_config_upsert', resource: 'remote_config', resourceId: item.id, outcome: 'SUCCESS', requestId, metadata: { configKey: dto.configKey } }); return item; }

  async getSubscriptionSettings() { const existing = await this.prisma.subscriptionSetting.findUnique({ where: { id: DEFAULT_SETTINGS_ID }, include: { defaultGroup: { select: { id: true, name: true } } } }); return existing ?? this.prisma.subscriptionSetting.create({ data: { id: DEFAULT_SETTINGS_ID } }); }
  async updateSubscriptionSettings(dto: SubscriptionSettingsDto, actor: AuthenticatedPrincipal, requestId: string) { const item = await this.prisma.subscriptionSetting.upsert({ where: { id: DEFAULT_SETTINGS_ID }, create: { id: DEFAULT_SETTINGS_ID, ...dto, updatedById: actor.id }, update: { ...dto, updatedById: actor.id } }); await this.audit.write({ actorId: actor.id, action: 'legacy.subscription_settings_update', resource: 'subscription_setting', resourceId: item.id, outcome: 'SUCCESS', requestId }); return item; }
  async createSubscriptionRequest(dto: CreateSubscriptionRequestDto, actor: AuthenticatedPrincipal, requestId: string) { const settings = await this.getSubscriptionSettings(); const months = dto.monthsAdded ?? 1; const start = new Date(); const end = new Date(start); end.setUTCMonth(end.getUTCMonth() + months); const detailsSnapshot = { monthlyAmountPkr: settings.monthlyAmountPkr, currency: settings.currency, defaultGroupId: settings.defaultGroupId, jazzcashNumber: settings.jazzcashNumber, easypaisaNumber: settings.easypaisaNumber, bankName: settings.bankName, paymentInstructions: settings.paymentInstructions }; const item = await this.prisma.subscriptionRequest.create({ data: { userId: actor.id, groupId: dto.groupId ?? settings.defaultGroupId, planId: dto.planId, amountPkr: dto.amountPkr ?? settings.monthlyAmountPkr * months, paymentMethod: dto.paymentMethod, screenshotKey: dto.screenshotKey, note: dto.note, monthsAdded: months, subscriptionStartDate: start, subscriptionEndDate: end, detailsSnapshot } }); await this.audit.write({ actorId: actor.id, action: 'legacy.subscription_request_create', resource: 'subscription_request', resourceId: item.id, outcome: 'SUCCESS', requestId }); return item; }
  async listSubscriptionRequests(query: LegacyListDto, actor: AuthenticatedPrincipal) { const where = actor.permissions.includes('subscriptions.read') ? {} : { userId: actor.id }; return this.page(this.prisma.subscriptionRequest, where, query, { createdAt: 'desc' }, { id: true, userId: true, groupId: true, planId: true, amountPkr: true, currency: true, paymentMethod: true, note: true, status: true, adminNote: true, invoiceNo: true, monthsAdded: true, subscriptionStartDate: true, subscriptionEndDate: true, approvedAt: true, rejectedAt: true, createdAt: true }); }
  async reviewSubscriptionRequest(id: string, dto: ReviewSubscriptionRequestDto, actor: AuthenticatedPrincipal, requestId: string) { const request = await this.prisma.subscriptionRequest.findUnique({ where: { id } }); if (!request) throw new NotFoundException('Subscription request not found'); if (request.status !== 'pending') throw new ConflictException('Subscription request was already reviewed'); if (dto.status === 'rejected') { const item = await this.prisma.subscriptionRequest.update({ where: { id }, data: { status: 'rejected', adminNote: dto.adminNote, rejectedAt: new Date() } }); await this.audit.write({ actorId: actor.id, action: 'legacy.subscription_request_reject', resource: 'subscription_request', resourceId: id, outcome: 'SUCCESS', requestId }); return item; } const start = dto.subscriptionStartDate ? new Date(dto.subscriptionStartDate) : request.subscriptionStartDate ?? new Date(); const end = dto.subscriptionEndDate ? new Date(dto.subscriptionEndDate) : request.subscriptionEndDate ?? new Date(start.getTime() + request.monthsAdded * 30 * 86400000); if (start >= end) throw new BadRequestException('Subscription dates are invalid'); const result = await this.prisma.$transaction(async (tx) => { const item = await tx.subscriptionRequest.update({ where: { id }, data: { status: 'approved', adminNote: dto.adminNote, approvedById: actor.id, approvedAt: new Date(), subscriptionStartDate: start, subscriptionEndDate: end, invoiceNo: request.invoiceNo ?? `UB-INV-${Date.now()}-${id.slice(0, 8).toUpperCase()}` } }); if (request.groupId) await tx.groupMember.upsert({ where: { groupId_userId: { groupId: request.groupId, userId: request.userId } }, create: { groupId: request.groupId, userId: request.userId, startsAt: start, endsAt: end, subscription: true }, update: { startsAt: start, endsAt: end, revokedAt: null, subscription: true } }); const plan = request.planId ? await tx.subscriptionPlan.findUnique({ where: { id: request.planId } }) : await tx.subscriptionPlan.findFirst({ where: { isActive: true }, orderBy: { createdAt: 'asc' } }); if (plan) { const subscription = await tx.subscription.create({ data: { userId: request.userId, planId: plan.id, startsAt: start, endsAt: end, status: 'ACTIVE', note: `Approved request ${item.id}` } }); await tx.paymentRecord.create({ data: { userId: request.userId, planId: plan.id, actorId: actor.id, amountPkr: request.amountPkr, method: 'OTHER', status: 'CONFIRMED', paidAt: new Date(), reference: item.invoiceNo } }); return { item, subscription }; } return { item, subscription: null }; }); await this.audit.write({ actorId: actor.id, action: 'legacy.subscription_request_approve', resource: 'subscription_request', resourceId: id, outcome: 'SUCCESS', requestId }); return result; }

  async getSecurityBlock(actor: AuthenticatedPrincipal) { const item = await this.prisma.securityBlock.findUnique({ where: { userId: actor.id }, select: { isBlocked: true, message: true, updatedAt: true } }); return item ?? { isBlocked: false, message: null }; }
  async setSecurityBlock(userId: string, dto: SecurityBlockDto, actor: AuthenticatedPrincipal, requestId: string) { await this.ensureUser(userId); const item = await this.prisma.securityBlock.upsert({ where: { userId }, create: { userId, isBlocked: dto.isBlocked, message: dto.message, blockedById: actor.id, blockedAt: dto.isBlocked ? new Date() : null }, update: { isBlocked: dto.isBlocked, message: dto.message, blockedById: actor.id, blockedAt: dto.isBlocked ? new Date() : null } }); await this.audit.write({ actorId: actor.id, action: dto.isBlocked ? 'legacy.security_block' : 'legacy.security_unblock', resource: 'security_block', resourceId: userId, outcome: 'SUCCESS', requestId }); return item; }
  async reportIncident(dto: SecurityIncidentDto, actor: AuthenticatedPrincipal, request: Request, requestId: string) { const item = await this.prisma.securityIncident.create({ data: { userId: actor.id, incidentType: dto.incidentType, incidentLabel: dto.incidentLabel, appArea: dto.appArea, deviceModel: dto.deviceModel, manufacturer: dto.manufacturer, androidVersion: dto.androidVersion, appVersion: dto.appVersion, appVersionCode: dto.appVersionCode, packageName: dto.packageName, deviceId: dto.deviceId, deviceBrand: dto.deviceBrand, deviceProduct: dto.deviceProduct, deviceHardware: dto.deviceHardware, deviceFingerprint: dto.deviceFingerprint, latitude: dto.latitude, longitude: dto.longitude, locationAccuracy: dto.locationAccuracy, extra: dto.extra as Prisma.InputJsonValue, severity: dto.severity ?? 'info', ipAddress: request.ip } }); await this.audit.write({ actorId: actor.id, action: 'legacy.security_incident_report', resource: 'security_incident', resourceId: item.id, outcome: 'SUCCESS', requestId }); return { success: true, id: item.id }; }
  async listIncidents(query: LegacyListDto) { return this.page(this.prisma.securityIncident, {}, query, { createdAt: 'desc' }, { id: true, userId: true, incidentType: true, incidentLabel: true, appArea: true, deviceModel: true, appVersion: true, appVersionCode: true, deviceId: true, severity: true, ipAddress: true, createdAt: true }); }
  async deleteIncident(id: string, actor: AuthenticatedPrincipal, requestId: string) { const result = await this.prisma.securityIncident.deleteMany({ where: { id } }); if (!result.count) throw new NotFoundException('Security incident not found'); await this.audit.write({ actorId: actor.id, action: 'legacy.security_incident_delete', resource: 'security_incident', resourceId: id, outcome: 'SUCCESS', requestId }); return { success: true }; }

  async listComments(episodeId: string, query: LegacyListDto) { return this.page(this.prisma.contentComment, { episodeId, status: 'visible' }, query, { createdAt: 'desc' }, { id: true, body: true, status: true, createdAt: true, user: { select: { id: true, username: true, profileImageKey: true } } }); }
  async createComment(dto: CreateCommentDto, actor: AuthenticatedPrincipal, requestId: string) { if (!dto.episodeId && !dto.groupId) throw new BadRequestException('episodeId or groupId is required'); const item = await this.prisma.contentComment.create({ data: { userId: actor.id, episodeId: dto.episodeId, groupId: dto.groupId, body: dto.body.trim() } }); await this.audit.write({ actorId: actor.id, action: 'legacy.comment_create', resource: 'content_comment', resourceId: item.id, outcome: 'SUCCESS', requestId }); return item; }
  async updateComment(id: string, dto: UpdateCommentDto, actor: AuthenticatedPrincipal, requestId: string) { const comment = await this.prisma.contentComment.findUnique({ where: { id } }); if (!comment) throw new NotFoundException('Comment not found'); if (comment.userId !== actor.id && !actor.permissions.includes('content.write')) throw new BadRequestException('Comment access denied'); const item = await this.prisma.contentComment.update({ where: { id }, data: { ...(dto.body !== undefined ? { body: dto.body.trim() } : {}), ...(dto.status !== undefined ? { status: dto.status } : {}) } }); await this.audit.write({ actorId: actor.id, action: 'legacy.comment_update', resource: 'content_comment', resourceId: id, outcome: 'SUCCESS', requestId }); return item; }
  async deleteComment(id: string, actor: AuthenticatedPrincipal, requestId: string) { const comment = await this.prisma.contentComment.findUnique({ where: { id } }); if (!comment) throw new NotFoundException('Comment not found'); if (comment.userId !== actor.id && !actor.permissions.includes('content.write')) throw new BadRequestException('Comment access denied'); await this.prisma.contentComment.update({ where: { id }, data: { status: 'hidden' } }); await this.audit.write({ actorId: actor.id, action: 'legacy.comment_delete', resource: 'content_comment', resourceId: id, outcome: 'SUCCESS', requestId }); return { success: true }; }

  async recordView(dto: RecordViewDto, actor: AuthenticatedPrincipal, request: Request) { const episode = await this.prisma.episode.findFirst({ where: { id: dto.episodeId, deletedAt: null }, select: { id: true } }); if (!episode) throw new NotFoundException('Episode not found'); return this.prisma.videoView.create({ data: { episodeId: dto.episodeId, userId: actor.id, ipAddress: request.ip, userAgent: request.get('user-agent')?.slice(0, 512) } }); }
  async analytics(query: LegacyListDto) { const where = query.search ? { episode: { title: { contains: query.search, mode: 'insensitive' as const } } } : {}; const [views, total, uniqueUsers] = await this.prisma.$transaction([this.prisma.videoView.findMany({ where, orderBy: { viewedAt: 'desc' }, skip: (query.page - 1) * query.limit, take: query.limit, select: { id: true, episodeId: true, userId: true, viewedAt: true, episode: { select: { id: true, title: true, episodeNumber: true } }, user: { select: { id: true, username: true, email: true } } } }), this.prisma.videoView.count({ where }), this.prisma.videoView.groupBy({ by: ['userId'], where, orderBy: { userId: 'asc' } })]); return { items: views, page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit), uniqueUsers: uniqueUsers.length }; }
  async dashboard() { const [users, activeUsers, dramas, seasons, episodes, activeSubscriptions, views, pendingRequests, unreadMessages] = await Promise.all([this.prisma.user.count({ where: { deletedAt: null } }), this.prisma.user.count({ where: { status: 'ACTIVE', deletedAt: null } }), this.prisma.drama.count({ where: { deletedAt: null } }), this.prisma.season.count({ where: { deletedAt: null } }), this.prisma.episode.count({ where: { deletedAt: null } }), this.prisma.subscription.count({ where: { status: 'ACTIVE', endsAt: { gt: new Date() } } }), this.prisma.videoView.count(), this.prisma.subscriptionRequest.count({ where: { status: 'pending' } }), this.prisma.userMessage.count({ where: { status: 'unread' } })]); return { users, activeUsers, dramas, seasons, episodes, activeSubscriptions, views, pendingSubscriptionRequests: pendingRequests, unreadMessages }; }
  async search(query: SearchDto, actor: AuthenticatedPrincipal) { const term = query.q.trim(); const [dramas, seasons, episodes, users] = await Promise.all([this.prisma.drama.findMany({ where: { name: { contains: term, mode: 'insensitive' }, deletedAt: null }, take: query.limit, select: { id: true, name: true, slug: true } }), this.prisma.season.findMany({ where: { title: { contains: term, mode: 'insensitive' }, deletedAt: null }, take: query.limit, select: { id: true, title: true, seasonNumber: true, dramaId: true } }), this.prisma.episode.findMany({ where: { OR: [{ title: { contains: term, mode: 'insensitive' } }, { description: { contains: term, mode: 'insensitive' } }], deletedAt: null }, take: query.limit, select: { id: true, title: true, episodeNumber: true, seasonId: true } }), actor.permissions.includes('users.read') ? this.prisma.user.findMany({ where: { OR: [{ username: { contains: term, mode: 'insensitive' } }, { email: { contains: term, mode: 'insensitive' } }], deletedAt: null }, take: query.limit, select: { id: true, username: true, email: true, status: true } }) : Promise.resolve([])]); return { dramas, seasons, episodes, users }; }

  async listAdmins(query: LegacyListDto) { const where = { deletedAt: null, roles: { some: { role: { code: { in: [RoleCode.SUPER_ADMIN, RoleCode.ADMIN, RoleCode.SUB_ADMIN, RoleCode.MODERATOR] } } } } }; return this.page(this.prisma.user, where, query, { createdAt: 'desc' }, { id: true, username: true, email: true, status: true, createdAt: true, roles: { select: { role: { select: { code: true, name: true } } } } }); }
  async createAdmin(dto: CreateAdminDto, actor: AuthenticatedPrincipal, requestId: string) { if (!ADMIN_ROLES.includes(dto.role) || dto.role === RoleCode.SUPER_ADMIN) throw new BadRequestException('Only non-owner administrative roles can be created here'); const email = dto.email.trim().toLowerCase(); const passwordHash = await argon2.hash(dto.password, { type: argon2.argon2id }); try { const user = await this.prisma.$transaction(async (tx) => { const created = await tx.user.create({ data: { username: dto.username.trim(), email, passwordHash, status: 'ACTIVE' } }); const role = await tx.roleDefinition.findUniqueOrThrow({ where: { code: dto.role } }); await tx.userRole.create({ data: { userId: created.id, roleId: role.id } }); return created; }); await this.audit.write({ actorId: actor.id, action: 'legacy.admin_create', resource: 'user', resourceId: user.id, outcome: 'SUCCESS', requestId, metadata: { role: dto.role } }); return { id: user.id, username: user.username, email: user.email, role: dto.role }; } catch (error) { if ((error as { code?: string }).code === 'P2002') throw new ConflictException('Email or username is already in use'); throw error; } }
  async assignAdminRole(userId: string, dto: AdminRoleDto, actor: AuthenticatedPrincipal, requestId: string) { if (!ADMIN_ROLES.includes(dto.role)) throw new BadRequestException('Invalid administrative role'); await this.ensureUser(userId); const role = await this.prisma.roleDefinition.findUnique({ where: { code: dto.role } }); if (!role) throw new NotFoundException('Role not found'); await this.prisma.userRole.upsert({ where: { userId_roleId: { userId, roleId: role.id } }, create: { userId, roleId: role.id }, update: {} }); await this.audit.write({ actorId: actor.id, action: 'legacy.admin_role_assign', resource: 'user', resourceId: userId, outcome: 'SUCCESS', requestId, metadata: { role: dto.role } }); return { success: true, userId, role: dto.role }; }
  async removeAdminRole(userId: string, dto: AdminRoleDto, actor: AuthenticatedPrincipal, requestId: string) { if (dto.role === RoleCode.SUPER_ADMIN) throw new BadRequestException('Super admin role cannot be removed through this endpoint'); const role = await this.prisma.roleDefinition.findUnique({ where: { code: dto.role } }); if (!role) throw new NotFoundException('Role not found'); const result = await this.prisma.userRole.deleteMany({ where: { userId, roleId: role.id } }); if (!result.count) throw new NotFoundException('Administrative role assignment not found'); await this.audit.write({ actorId: actor.id, action: 'legacy.admin_role_remove', resource: 'user', resourceId: userId, outcome: 'SUCCESS', requestId, metadata: { role: dto.role } }); return { success: true }; }

  private async page(model: { findMany: Function; count: Function }, where: object, query: LegacyListDto, orderBy: object, select: object) { const [items, total] = await Promise.all([model.findMany({ where, orderBy, skip: (query.page - 1) * query.limit, take: query.limit, select }), model.count({ where })]); return { items, page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) }; }
  private publicRelease(item: { id: string; versionName: string | null; versionCode: number | null; originalName: string | null; fileSize: bigint | null; isActive: boolean; createdAt: Date }) { return { id: item.id, versionName: item.versionName, versionCode: item.versionCode, originalName: item.originalName, fileSize: item.fileSize?.toString() ?? null, isActive: item.isActive, createdAt: item.createdAt, downloadPath: `/api/v1/app/releases/${item.id}/download` }; }
  private async ensureUser(id: string) { const user = await this.prisma.user.findFirst({ where: { id, deletedAt: null }, select: { id: true } }); if (!user) throw new NotFoundException('User not found'); }
  private async ensureDrama(id: string) { const drama = await this.prisma.drama.findFirst({ where: { id, deletedAt: null }, select: { id: true } }); if (!drama) throw new NotFoundException('Drama not found'); }
  private async tokensForUsers(ids: string[]) { const users = await this.prisma.user.findMany({ where: { id: { in: ids }, deviceToken: { not: null } }, select: { deviceToken: true } }); return users.map((user) => user.deviceToken ?? ''); }
  private async pushToUser(userId: string, title: string, body: string, data: Record<string, string>) { const tokens = await this.tokensForUsers([userId]); return this.push.send(tokens, title, body, data); }
}
