import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().port().default(3000),
  PUBLIC_API_ORIGIN: Joi.when('NODE_ENV', { is: 'production', then: Joi.string().uri({ scheme: ['https'] }), otherwise: Joi.string().uri({ scheme: ['http', 'https'] }) }).required(),
  ADMIN_WEB_ORIGIN: Joi.when('NODE_ENV', { is: 'production', then: Joi.string().uri({ scheme: ['https'] }), otherwise: Joi.string().uri({ scheme: ['http', 'https'] }) }).required(),
  DATABASE_URL: Joi.string().uri({ scheme: ['postgresql', 'postgres'] }).required(),
  REDIS_URL: Joi.string().uri({ scheme: ['redis', 'rediss'] }).required(),
  JWT_ISSUER: Joi.string().min(3).max(100).required(),
  JWT_AUDIENCE: Joi.string().min(3).max(100).required(),
  JWT_PRIVATE_KEY_B64: Joi.string().min(100).required(),
  JWT_PUBLIC_KEY_B64: Joi.string().min(100).required(),
  JWT_ACCESS_TTL_SECONDS: Joi.number().integer().min(60).max(900).default(600),
  REFRESH_TOKEN_TTL_DAYS: Joi.number().integer().min(1).max(90).default(30),
  TRUSTED_PROXY_HOPS: Joi.number().integer().min(0).max(5).default(0),
  LOG_LEVEL: Joi.string().valid('fatal', 'error', 'warn', 'info', 'debug', 'trace').default('info'),
  ENABLE_SWAGGER: Joi.boolean().truthy('true').falsy('false').default(false),
  METRICS_TOKEN: Joi.string().min(32).required(),
  FIREBASE_SERVICE_ACCOUNT_B64: Joi.string().base64().allow('').default(''),
  WIDEVINE_PROVIDER: Joi.string().max(80).allow('').default(''),
  WIDEVINE_LICENSE_URL: Joi.string().uri({ scheme: ['https'] }).allow('').default(''),
  ARGON2_DUMMY_HASH: Joi.string().min(20).required(),
  MEDIA_GATEWAY_PUBLIC_URL: Joi.string().uri({ scheme: ['https'] }).required(),
  MEDIA_LOCATOR_ENCRYPTION_KEY_B64: Joi.string().base64().required(),
  MEDIA_PROVIDER_ALLOWED_HOSTS: Joi.string().min(3).required(),
  MEDIA_PROVIDER_ORIGIN_SECRET: Joi.string().min(32).required(),
  MEDIA_PROVIDER_TIMEOUT_MS: Joi.number().integer().min(1000).max(30000).default(10000),
  UPLOAD_STAGING_DIR: Joi.string().default('.runtime/uploads'),
  MAX_UPLOAD_BYTES: Joi.number().integer().min(1).max(20000000000).default(20000000000),
  STORAGE_UPLOAD_URL: Joi.string().uri({ scheme: ['https'] }).allow('').default(''),
  STORAGE_UPLOAD_TOKEN: Joi.string().allow('').default(''),
  R2_ACCOUNT_ID: Joi.string().allow('').default(''),
  R2_ACCESS_KEY_ID: Joi.string().allow('').default(''),
  R2_SECRET_ACCESS_KEY: Joi.string().allow('').default(''),
  R2_BUCKET: Joi.string().allow('').default(''),
  R2_PUBLIC_BASE_URL: Joi.string().uri({ scheme: ['https'] }).allow('').default(''),
  PLAYBACK_CAPABILITY_TTL_SECONDS: Joi.number().integer().min(30).max(300).default(120),
  MAX_CONCURRENT_PLAYBACK_SESSIONS: Joi.number().integer().min(1).max(5).default(1),
  MAX_TRUSTED_DEVICES: Joi.number().integer().min(1).max(10).default(3),
});
